### ISSUE TITLE
package_weight is returned 0 for some products

### ISSUE THREAD

**Issue by nitin-magento** [webshopapps/module-matrixrate#100]
Hello webshopapps team,

Strange issue, any help much appreciated!

Strangely **only some products** are returning weight 0 so matrix rate is not working for those products.
When checked in database the products values stored are there in the database but just not reflecting on the shopping cart.

Re-importing does not help, csv file is correct and working for most products.

When I debugged being a dev, placed this code in file /vendor/webshopapps/module-matrixrate/src/Model/ResourceModel/Carrier/Matrixrate.php
` $this->logger->debug(print_r($request->getData('package_weight'), true));`
is returning 0 in case of faulty products.

What can you suggest please?

**Comment by WSAlewis** [comment]
Hello Nitin,

Thanks for reaching out to us.

It appears that you're running into an issue indexing here. Unfortunately, MatrixRates is a free, unsupported product so I'm unable to delve deeper into this with you. We do offer a wide selection of documentation that should help you answer your questions, though, and those can be found here. Thanks!

https://docs.shipperhq.com/?s=matrixrate
http://support.webshopapps.com/matrixrate/

**Comment by Azaciux** [comment]
Hello, 

Just for anyone looking at this in future. The reason why package_weight could be returned as 0 is due to the way the module handles Free Shipping.

In my case, it turned out I had an old yet still enabled Cart Price Rule which was setting the shipping to free, and taking off the weight & qty (as expected) of the remaining requested items.

Also in my case, Free Shipping was disabled. So the module would just say "No shipping available".

Hope this helps someone in future!

Cheers
