### ISSUE TITLE
Issue with preselect method

### ISSUE THREAD

**Issue by AlexanderKopyl** [webshopapps/module-matrixrate#108]
If we have different shipping method by the price but the same title
and we selected one of them and change price preselected method disappear

**Comment by wsadasmit** [comment]
Hi @AlexanderKopyl 

I'm not sure what you mean here without more detail. This sounds like it could be a configuration issue, in which case I suggest you review our [documentation on this module](https://docs.shipperhq.com/category/basic-setup/webshopapps-extensions/matrixrates/) as we do not provide active support for this free module.

If you're confident you've configured things correctly, please provide full details to recreate this issue so that we may replicate it in our own environment, including conditions for this to occur and a list of complete steps to trigger it. Please attach your csv as well so that we may review it.

Feel free to email support@shipperhq.com to continue this conversation by email if you prefer.
