### ISSUE TITLE
What is the meaning of cost? No cost column in csv!

### ISSUE THREAD

**Issue by cptX** [webshopapps/module-matrixrate#118]
I checked the database and there is a column "cost".
Also, in file /Model/Carrier/Matrixrate.php there is this line `$method->setCost($rate['cost']);`
which doesn't make sense as the generated matrixrates.csv file doesn't have any "cost" column!

So can you please explain what is the meaning of cost here? Do we need it? Is the Cost forgotten to be added as a column in the generated csv?

**Comment by PeterElkoShipperHQ** [comment]
Hi  @cptX ,

I'm Peter a support engineer here at ShipperHQ. Cost is not used in MatrixRate, which is why it is not included in the CSV. The column "cost" is present, because it is present in the core Magento table rates, which MatrixRate is based on.

Please let us know if you have any further questions.

Have a great night!
Peter
ShipperHQ Support
