### ISSUE TITLE
Free shipping for tablerates metod will hide Matrixrate shipment option as well

### ISSUE THREAD

**Issue by onepack** [webshopapps/module-matrixrate#74]
I created a free-shipment rule that only applies to Table-rates. 
In the free shipment promotion rule I selected "if shipment method is Tablerates". However, the whole matrix-method will disappear when I enable this promotion. Only table rates shows with price = 0.
Disabling the promotion will show both options again.

**Comment by onepack** [comment]
Setting "Show Method if Not Applicable" to yes will show the shipping method in the frontend as 0 with the message:
This shipping method is not available. To use this shipping method, please contact us.
So clearly the rule applies to matrix as well and sets it to 0.
I will solve this now by setting free shipments above 100 etc in the .csv files so that I don't need these rules.

**Comment by wsajosh** [comment]
Apologies for the delayed reply. MatrixRate has limited support for free promotion rules. The rule you've set up will apply to all shipping methods rather than just Table Rate. If MatrixRate detects that a free promo rule has been applied, it will set all of its available methods to free shipping. It does rely on there being a valid rate within the CSV for the current cart. If there's not, then you'd see the type of behaviour that you've outlined here. Glad you managed to work around the issue though.
