### ISSUE TITLE
Customer save address is duplicated on checkout

### ISSUE THREAD

**Issue by NTK-2016** [webshopapps/module-matrixrate#94]
Matrixrate have an issue with subtotal vs destination condition issue ,it duplicated customer saved address
![image](https://user-images.githubusercontent.com/24722367/97431458-56cfea80-1940-11eb-862b-2ae4d05f39c0.png)

**Comment by ibraheemnabeelfauzi** [comment]
Hi @NTK-2016 

Can you please clarify what do you mean by the subtotal vs destination condition issue? You're using a OSC which re-wires the core Magento checkout that we written the MatrixRates to work with which introduces different issues.

**Comment by NTK-2016** [comment]
yes ,i'm using OSC which creating an issue

**Comment by NTK-2016** [comment]
@ibraheemnabeelfauzi  any update

**Comment by ibraheemnabeelfauzi** [comment]
Hi @NTK-2016  I'm still not clear on what the problem is and unfortunately we don't actively support the MatrixRates as it's a free extension - we only provide documentation: http://support.webshopapps.com/productmatrix/known-onestepcheckout-osc-issue/

https://docs.shipperhq.com/troubleshooting-matrixrates/

**Comment by NTK-2016** [comment]
Hi @ibraheemnabeelfauzi , let me to clear my question . The issue with  extension is ."When customer place order it's billing address is duplicated after payment is successful.

**Comment by wsajosh** [comment]
Hi, This is an issue with your checkout rather than MatrixRate. MatrixRate has no control over the addresses in checkout. I'm closing this issue.
